import cripto1 from "../../assets/images/svg/crypto-icons/0xbtc.svg";
import cripto2 from "../../assets/images/svg/crypto-icons/abt.svg";
import cripto3 from "../../assets/images/svg/crypto-icons/add.svg";
import cripto4 from "../../assets/images/svg/crypto-icons/adx.svg";

import icon1 from "../../assets/images/companies/img-1.png";
import icon2 from "../../assets/images/companies/img-2.png";
import icon3 from "../../assets/images/companies/img-3.png";
import icon4 from "../../assets/images/companies/img-4.png";

import gif1 from "../../assets/images/nft/gif/img-1.gif";
import gif2 from "../../assets/images/nft/gif/img-2.gif";
import gif3 from "../../assets/images/nft/gif/img-3.gif";
import gif4 from "../../assets/images/nft/gif/img-4.gif";

export const fakeTransactions = [
  {
    action: "Receive",
    img: cripto1,
    hour: "12:00",
    fee: "0x4b8d...",
    img2: icon1,
    date: "January 1, 2023",
    info: "N/A",
    hash: "0.0001",
    img3: gif1,
    from: "0x4b8d...",
  },
  {
    action: "Collect",
    img: cripto2,
    hour: "15:30",
    hash: "0x5f6e...",
    img2: icon2,
    date: "February 12, 2023",
    info: "1.050,50 US$",
    fee: "0x4b8d...",
    img3: gif3,
    from: "0x5f6e...",
    collection: "Exclusive NFTs",
    action2: [{ title: "Sent", img: icon2 }],
    received: [
      { img: gif1, amount: "500.00 US$" },
      { img: gif2, amount: "300.00 US$" },
      { img: gif3, amount: "250.50 US$" },
    ],
  },
  {
    action: "Trade",
    img: cripto3,
    hour: "12:00",
    fee: "0x4b8d...",
    img2: icon2,
    date: "June 2, 2023",
    info: "11.372,40 US$",
    hash: "0.0001",
    img3: gif4,
    from: "0x4b8d...",
  },
  {
    action: "Auction",
    img: cripto4,
    hour: "18:45",
    hash: "0x7a2d...",
    img2: icon3,
    date: "April 22, 2023",
    info: "Sold for 3.200,00 US$",
    fee: "0x4b8d...",
    img3: gif2,
    from: "0x7a2d...",
    collection: "Rare Artifacts",
    action2: [{ title: "Sent", img: icon3 }],
    received: [
      { img: icon4, amount: "1.200,00 US$" },
      { img: icon2, amount: "1.000,00 US$" },
      { img: icon3, amount: "1.000,00 US$" },
    ],
  },
  {
    action: "Mint",
    img: cripto3,
    hour: "12:00",
    fee: "0x4b8d...",
    img2: icon3,
    date: "August 26, 2023",
    info: "N/A",
    hash: "0.0001",
    img3: gif2,
    from: "0x4b8d...",
  },
  {
    action: "Swap",
    img: cripto2,
    hour: "10:15",
    hash: "0x9b0c...",
    img2: icon3,
    date: "July 8, 2023",
    info: "Swapped with Item XYZ",
    fee: "0x4b8d...",
    img3: gif4,
    from: "0x9b0c...",
    collection: "Digital Assets",
    action2: [{ title: "Sent", img: icon3 }],
    received: [
      { img: gif3, amount: "2.000,00 US$" },
      { img: gif1, amount: "3.500,00 US$" },
      { img: icon1, amount: "4.500,00 US$" },
    ],
  },
  {
    action: "Send",
    img: cripto4,
    hour: "12:00",
    img2: icon4,
    fee: "0x4b8d...",
    date: "November 4, 2023",
    info: "N/A",
    hash: "0.0001",
    img3: gif1,
    from: "0x4b8d...",
  },
  {
    action: "Approve",
    img: cripto1,
    hour: "12:00",
    fee: "0x4b8d...",
    img2: icon2,
    date: "December 1, 2023",
    info: "N/A",
    hash: "0.0001",
    img3: gif3,
    from: "0x4b8d...",
  },
  {
    action: "executed",
    img: cripto2,
    hour: "12:00",
    img2: icon1,
    fee: "0x4b8d...",
    info: "N/A",
    date: "March 1, 2023",
    info: "4743,28 US$",
    hash: "0.0001",
    img3: gif2,
    from: "0x4b8d...",
  },
  {
    action: "success",
    img: cripto3,
    hour: "12:00",
    fee: "0x4b8d...",
    img2: icon3,
    date: "September 14, 2023",
    info: "82,25 US$",
    hash: "0.0001",
    img3: gif4,
    from: "0x4b8d...",
  },
];
