export const timezonesArray = [
  { key: '', label: 'Auto' },
  { key: 'Etc/GMT+12', label: '(UTC-12:00) International Date Line West' },
  { key: 'Etc/GMT+11', label: '(UTC-11:00) Coordinated Universal Time-11' },
  { key: 'Etc/GMT+10', label: '(UTC-10:00) Hawaii' },
  { key: 'America/Anchorage', label: '(UTC-09:00) Alaska' },
  { key: 'America/Santa_Isabel', label: '(UTC-08:00) Baja California' },
  {
    key: 'America/Los_Angeles',
    label: '(UTC-08:00) Pacific Time (US & Canada)',
  },
  { key: 'Etc/GMT+7', label: '(UTC-07:00) Arizona' },
  {
    key: 'America/Chihuahua',
    label: '(UTC-07:00) Chihuahua, La Paz, Mazatlan',
  },
  { key: 'America/Denver', label: '(UTC-07:00) Mountain Time (US & Canada)' },
  { key: 'Etc/GMT+6', label: '(UTC-06:00) Central America' },
  { key: 'America/Chicago', label: '(UTC-06:00) Central Time (US & Canada)' },
  {
    key: 'America/Mexico_City',
    label: '(UTC-06:00) Guadalajara, Mexico City, Monterrey',
  },
  { key: 'America/Regina', label: '(UTC-06:00) Saskatchewan' },
  { key: 'Etc/GMT+5', label: '(UTC-05:00) Bogota, Lima, Quito' },
  { key: 'America/New_York', label: '(UTC-05:00) Eastern Time (US & Canada)' },
  { key: 'America/Indianapolis', label: '(UTC-05:00) Indiana (East)' },
  { key: 'America/Caracas', label: '(UTC-04:30) Caracas' },
  { key: 'America/Asuncion', label: '(UTC-04:00) Asuncion' },
  { key: 'America/Halifax', label: '(UTC-04:00) Atlantic Time (Canada)' },
  { key: 'America/Cuiaba', label: '(UTC-04:00) Cuiaba' },
  {
    key: 'Etc/GMT+4',
    label: '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan',
  },
  { key: 'America/Santiago', label: '(UTC-04:00) Santiago' },
  { key: 'America/St_Johns', label: '(UTC-03:30) Newfoundland' },
  { key: 'America/Sao_Paulo', label: '(UTC-03:00) Brasilia' },
  { key: 'America/Buenos_Aires', label: '(UTC-03:00) Buenos Aires' },
  { key: 'Etc/GMT+3', label: '(UTC-03:00) Cayenne, Fortaleza' },
  { key: 'America/Godthab', label: '(UTC-03:00) Greenland' },
  { key: 'America/Montevideo', label: '(UTC-03:00) Montevideo' },
  { key: 'America/Bahia', label: '(UTC-03:00) Salvador' },
  { key: 'Etc/GMT+2', label: '(UTC-02:00) Coordinated Universal Time-02' },
  { key: 'Etc/GMT+2', label: '(UTC-02:00) Mid-Atlantic' },
  { key: 'Atlantic/Azore', label: '(UTC-01:00) Azores' },
  { key: 'Etc/GMT+1', label: '(UTC-01:00) Cape Verde Is.' },
  { key: 'Africa/Casablanca', label: '(UTC) Casablanca' },
  { key: 'Etc/GMT', label: '(UTC) Coordinated Universal Time' },
  { key: 'Europe/London', label: '(UTC) Dublin, Edinburgh, Lisbon, London' },
  { key: 'Atlantic/Reykjavik', label: '(UTC) Monrovia, Reykjavik' },
  {
    key: 'Europe/Berlin',
    label: '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
  },
  {
    key: 'Europe/Budapest',
    label: '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
  },
  {
    key: 'Europe/Paris',
    label: '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',
  },
  {
    key: 'Europe/Warsaw',
    label: '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
  },
  { key: 'Etc/GMT-1', label: '(UTC+01:00) West Central Africa' },
  { key: 'Africa/Windhoek', label: '(UTC+01:00) Windhoek' },
  { key: 'Europe/Bucharest', label: '(UTC+02:00) Athens, Bucharest' },
  { key: 'Asia/Beirut', label: '(UTC+02:00) Beirut' },
  { key: 'Africa/Cairo', label: '(UTC+02:00) Cairo' },
  { key: 'Asia/Damascus', label: '(UTC+02:00) Damascus' },
  { key: 'Asia/Nicosia', label: '(UTC+02:00) E. Europe' },
  { key: 'Africa/Johannesburg', label: '(UTC+02:00) Harare, Pretoria' },
  {
    key: 'Europe/Kiev',
    label: '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
  },
  { key: 'Europe/Istanbul', label: '(UTC+02:00) Istanbul' },
  { key: 'Asia/Jerusalem', label: '(UTC+02:00) Jerusalem' },
  { key: 'Asia/Amman', label: '(UTC+03:00) Amman' },
  { key: 'Asia/Baghdad', label: '(UTC+03:00) Baghdad' },
  { key: 'Europe/Kaliningrad', label: '(UTC+03:00) Kaliningrad, Minsk' },
  { key: 'Asia/Riyadh', label: '(UTC+03:00) Kuwait, Riyadh' },
  { key: 'Africa/Nairobi', label: '(UTC+03:00) Nairobi' },
  { key: 'Asia/Tehran', label: '(UTC+03:30) Tehran' },
  { key: 'Asia/Dubai', label: '(UTC+04:00) Abu Dhabi, Muscat' },
  { key: 'Asia/Baku', label: '(UTC+04:00) Baku' },
  {
    key: 'Europe/Moscow',
    label: '(UTC+04:00) Moscow, St. Petersburg, Volgograd',
  },
  { key: 'Indian/Mauritius', label: '(UTC+04:00) Port Louis' },
  { key: 'Asia/Tbilisi', label: '(UTC+04:00) Tbilisi' },
  { key: 'Asia/Yerevan', label: '(UTC+04:00) Yerevan' },
  { key: 'Asia/Kabul', label: '(UTC+04:30) Kabul' },
  { key: 'Asia/Karachi', label: '(UTC+05:00) Islamabad, Karachi' },
  { key: 'Etc/GMT-5', label: '(UTC+05:00) Tashkent' },
  {
    key: 'Asia/Calcutta',
    label: '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
  },
  { key: 'Asia/Colombo', label: '(UTC+05:30) Sri Jayawardenepura' },
  { key: 'Asia/Katmandu', label: '(UTC+05:45) Kathmandu' },
  { key: 'Etc/GMT-6', label: '(UTC+06:00) Astana' },
  { key: 'Asia/Dhaka', label: '(UTC+06:00) Dhaka' },
  { key: 'Asia/Yekaterinburg', label: '(UTC+06:00) Ekaterinburg' },
  { key: 'Asia/Rangoon', label: '(UTC+06:30) Yangon (Rangoon)' },
  { key: 'Asia/Bangkok', label: '(UTC+07:00) Bangkok, Hanoi, Jakarta' },
  { key: 'Asia/Novosibirsk', label: '(UTC+07:00) Novosibirsk' },
  {
    key: 'Asia/Shanghai',
    label: '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
  },
  { key: 'Asia/Krasnoyarsk', label: '(UTC+08:00) Krasnoyarsk' },
  { key: 'Etc/GMT-8', label: '(UTC+08:00) Kuala Lumpur, Singapore' },
  { key: 'Australia/Perth', label: '(UTC+08:00) Perth' },
  { key: 'Asia/Taipei', label: '(UTC+08:00) Taipei' },
  { key: 'Asia/Ulaanbaatar', label: '(UTC+08:00) Ulaanbaatar' },
  { key: 'Asia/Irkutsk', label: '(UTC+09:00) Irkutsk' },
  { key: 'Etc/GMT-9', label: '(UTC+09:00) Osaka, Sapporo, Tokyo' },
  { key: 'Asia/Seoul', label: '(UTC+09:00) Seoul' },
  { key: 'Australia/Adelaide', label: '(UTC+09:30) Adelaide' },
  { key: 'Australia/Darwin', label: '(UTC+09:30) Darwin' },
  { key: 'Australia/Brisbane', label: '(UTC+10:00) Brisbane' },
  { key: 'Australia/Sydney', label: '(UTC+10:00) Canberra, Melbourne, Sydney' },
  { key: 'Etc/GMT-10', label: '(UTC+10:00) Guam, Port Moresby' },
  { key: 'Australia/Hobart', label: '(UTC+10:00) Hobart' },
  { key: 'Asia/Yakutsk', label: '(UTC+10:00) Yakutsk' },
  { key: 'Etc/GMT-11', label: '(UTC+11:00) Solomon Is., New Caledonia' },
  { key: 'Asia/Vladivostok', label: '(UTC+11:00) Vladivostok' },
  { key: 'Pacific/Auckland', label: '(UTC+12:00) Auckland, Wellington' },
  { key: 'Etc/GMT-12', label: '(UTC+12:00) Coordinated Universal Time+12' },
  { key: 'Pacific/Fiji', label: '(UTC+12:00) Fiji' },
  { key: 'Asia/Magadan', label: '(UTC+12:00) Magadan' },
  { key: 'Etc/GMT-13', label: "(UTC+13:00) Nuku'alofa" },
  { key: 'Pacific/Apia', label: '(UTC+13:00) Samoa' },
];
