version: '3.8'

services:
  mongo:
    image: mongo
    container_name: "scrabble_mongo"
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: "scrabble"
      MONGO_INITDB_ROOT_PASSWORD: "scrabble"
    ports:
      - '27018:27017'
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: